### ISSUE TITLE
Error prompt

### ISSUE THREAD

**Issue by WingOfChicken** [masamesa/Twitch-Clip-Archiver#2]
Hey there,

Received this error, it said to post a screenshot here... so..

https://gyazo.com/0526e510e3d025e578f796046776afe8

Thanks, was working well until then!

**Comment by masamesa** [comment]
Hey there @WingOfChicken, do you mind telling me if this is on the latest version(1.1?) It appears like this could be an API issue so I'll look into it. If you don't mind filling this out, I'd greatly appreciate it:

What version are you using:
Is your Client ID correct?:
What steps did you do to replicate this issue:

**Comment by masamesa** [comment]
I just looked through it and it appears you're using an outdated version, please update to version 1.1, there's much better error handling.  https://github.com/masamesa/Twitch-Clip-Archiver/releases/tag/1.1

I have a feeling I what might have happened, either you got rate limited(unlikely) or the clip got deleted before it was able to be downloaded. I'll write some more code and possibly push another update by tonight so that way everything is handled a little better. 

Thanks for the report,
Alexander

**Comment by WingOfChicken** [comment]
Thanks for the quick response.

You're right (I'm dumb) and was using v1.0 instead of v1.1.    I've since updated to v1.1  but now have a different issued. No error code, but it seems to be getting stuck in a loop during the initial scanning phase.

It will initiate the scan, posting all the links as expected - then at some stage will start repeating the last ~50 or so links.

**Comment by masamesa** [comment]
No problem, we all make mistakes! Let me read through the code real quick and see if I can figure out why that's happening. Do you mind Sharing the twitch you're trying to archive clips from?

**Comment by WingOfChicken** [comment]
Sure, the channel is 'Bustin'.

I should mention it's looping between these two clips:

CrypticComfortableShallotTheThing
SilkyGorgeousSangFUNgineer

**Comment by masamesa** [comment]
Thanks! I fixed the issue; I'll be creating the binaries and uploading them momentarily here. I greatly appreciate the bug reporting! 

I haven't slept very much so I overlooked something when I added in the error handling and I was testing it on a smaller channel so I didn't pick that bug up. So pardon how buggy this is, the majority of this has been coded during a foggy state of mind. This really should be the last major bug, I have a few minor tweaks I intend to deploy out through the week, but nothing too ground breaking.

**Comment by masamesa** [comment]
Version 1,2 is released(https://github.com/masamesa/Twitch-Clip-Archiver/releases/tag/1.2). If you're still having this issue I'll keep this thread open for 12 hours. However, if  by chance you're having a new issue I'll request you open a new ticket. 

If you have any further comments, questions or concerns you're free to leave them here or direct message me on twitter: https://twitter.com/_MasaMesa

Thanks, 
Alexander

**Comment by WingOfChicken** [comment]
Thanks again for your prompt responses.

v1.2 did solve the looping issue, I have encountered another crash - but as requested I'll log that as a new issue.
